-- Extended candidate concept inventory (numbers, colors, calendar, people, actions, questions,
-- feelings, home, food, clothing, body & health, communication & accessibility, places,
-- public services, education & work, nature, religion & holidays, descriptions).
-- CANDIDATE CONCEPTS for coverage planning only — NOT validated ISL translations.
-- No sign entry, sign form or animation is created. Existing concepts are left untouched.
INSERT OR IGNORE INTO lexical_concepts (concept_key, category, hebrew_terms_json, english_terms_json, status, created_at, updated_at) VALUES
  ('ZERO', 'numbers', '["אפס"]', '["zero"]', 'candidate', 0, 0),
  ('ONE', 'numbers', '["אחד", "אחת"]', '["one"]', 'candidate', 0, 0),
  ('TWO', 'numbers', '["שתיים", "שניים", "שני", "שתי"]', '["two"]', 'candidate', 0, 0),
  ('THREE', 'numbers', '["שלוש", "שלושה"]', '["three"]', 'candidate', 0, 0),
  ('FOUR', 'numbers', '["ארבע", "ארבעה"]', '["four"]', 'candidate', 0, 0),
  ('FIVE', 'numbers', '["חמש", "חמישה"]', '["five"]', 'candidate', 0, 0),
  ('SIX', 'numbers', '["שש", "שישה"]', '["six"]', 'candidate', 0, 0),
  ('SEVEN', 'numbers', '["שבע", "שבעה"]', '["seven"]', 'candidate', 0, 0),
  ('EIGHT', 'numbers', '["שמונה"]', '["eight"]', 'candidate', 0, 0),
  ('NINE', 'numbers', '["תשע", "תשעה"]', '["nine"]', 'candidate', 0, 0),
  ('TEN', 'numbers', '["עשר", "עשרה"]', '["ten"]', 'candidate', 0, 0),
  ('HUNDRED', 'numbers', '["מאה"]', '["hundred"]', 'candidate', 0, 0),
  ('THOUSAND', 'numbers', '["אלף"]', '["thousand"]', 'candidate', 0, 0),
  ('HALF', 'numbers', '["חצי"]', '["half"]', 'candidate', 0, 0),
  ('NUMBER', 'numbers', '["מספר"]', '["number"]', 'candidate', 0, 0),
  ('COLOR', 'colors', '["צבע"]', '["color"]', 'candidate', 0, 0),
  ('RED', 'colors', '["אדום", "אדומה"]', '["red"]', 'candidate', 0, 0),
  ('BLUE', 'colors', '["כחול", "כחולה"]', '["blue"]', 'candidate', 0, 0),
  ('GREEN', 'colors', '["ירוק", "ירוקה"]', '["green"]', 'candidate', 0, 0),
  ('YELLOW', 'colors', '["צהוב", "צהובה"]', '["yellow"]', 'candidate', 0, 0),
  ('BLACK', 'colors', '["שחור", "שחורה"]', '["black"]', 'candidate', 0, 0),
  ('WHITE', 'colors', '["לבן", "לבנה"]', '["white"]', 'candidate', 0, 0),
  ('ORANGE_COLOR', 'colors', '["כתום", "כתומה"]', '["orange"]', 'candidate', 0, 0),
  ('PURPLE', 'colors', '["סגול", "סגולה"]', '["purple"]', 'candidate', 0, 0),
  ('BROWN', 'colors', '["חום", "חומה"]', '["brown"]', 'candidate', 0, 0),
  ('GRAY', 'colors', '["אפור", "אפורה"]', '["gray"]', 'candidate', 0, 0),
  ('PINK', 'colors', '["ורוד", "ורודה"]', '["pink"]', 'candidate', 0, 0),
  ('SUNDAY', 'calendar', '["יום ראשון"]', '["Sunday"]', 'candidate', 0, 0),
  ('MONDAY', 'calendar', '["יום שני"]', '["Monday"]', 'candidate', 0, 0),
  ('TUESDAY', 'calendar', '["יום שלישי"]', '["Tuesday"]', 'candidate', 0, 0),
  ('WEDNESDAY', 'calendar', '["יום רביעי"]', '["Wednesday"]', 'candidate', 0, 0),
  ('THURSDAY', 'calendar', '["יום חמישי"]', '["Thursday"]', 'candidate', 0, 0),
  ('FRIDAY', 'calendar', '["יום שישי"]', '["Friday"]', 'candidate', 0, 0),
  ('SATURDAY_SHABBAT', 'calendar', '["שבת", "יום שבת"]', '["Saturday", "Shabbat"]', 'candidate', 0, 0),
  ('DAY', 'calendar', '["יום"]', '["day"]', 'candidate', 0, 0),
  ('HOUR', 'calendar', '["שעה"]', '["hour"]', 'candidate', 0, 0),
  ('MINUTE', 'calendar', '["דקה"]', '["minute"]', 'candidate', 0, 0),
  ('DATE', 'calendar', '["תאריך"]', '["date"]', 'candidate', 0, 0),
  ('BIRTHDAY', 'calendar', '["יום הולדת"]', '["birthday"]', 'candidate', 0, 0),
  ('CALENDAR', 'calendar', '["לוח שנה", "יומן"]', '["calendar"]', 'candidate', 0, 0),
  ('EARLY', 'calendar', '["מוקדם"]', '["early"]', 'candidate', 0, 0),
  ('LATE', 'calendar', '["מאוחר", "מאחר"]', '["late"]', 'candidate', 0, 0),
  ('ALWAYS', 'calendar', '["תמיד"]', '["always"]', 'candidate', 0, 0),
  ('NEVER', 'calendar', '["אף פעם", "לעולם לא"]', '["never"]', 'candidate', 0, 0),
  ('SOMETIMES', 'calendar', '["לפעמים"]', '["sometimes"]', 'candidate', 0, 0),
  ('AGAIN', 'calendar', '["שוב", "עוד פעם"]', '["again"]', 'candidate', 0, 0),
  ('SOON', 'calendar', '["בקרוב"]', '["soon"]', 'candidate', 0, 0),
  ('ALREADY', 'calendar', '["כבר"]', '["already"]', 'candidate', 0, 0),
  ('STILL', 'calendar', '["עדיין"]', '["still"]', 'candidate', 0, 0),
  ('MAN', 'people_family', '["איש", "גבר"]', '["man"]', 'candidate', 0, 0),
  ('WOMAN', 'people_family', '["אישה"]', '["woman"]', 'candidate', 0, 0),
  ('BABY', 'people_family', '["תינוק", "תינוקת"]', '["baby"]', 'candidate', 0, 0),
  ('GRANDFATHER', 'people_family', '["סבא"]', '["grandfather"]', 'candidate', 0, 0),
  ('GRANDMOTHER', 'people_family', '["סבתא"]', '["grandmother"]', 'candidate', 0, 0),
  ('SON', 'people_family', '["בן"]', '["son"]', 'candidate', 0, 0),
  ('DAUGHTER', 'people_family', '["בת"]', '["daughter"]', 'candidate', 0, 0),
  ('HUSBAND', 'people_family', '["בעל"]', '["husband"]', 'candidate', 0, 0),
  ('WIFE', 'people_family', '["אשתי", "אישה"]', '["wife"]', 'candidate', 0, 0),
  ('UNCLE', 'people_family', '["דוד"]', '["uncle"]', 'candidate', 0, 0),
  ('AUNT', 'people_family', '["דודה"]', '["aunt"]', 'candidate', 0, 0),
  ('COUSIN', 'people_family', '["בן דוד", "בת דודה"]', '["cousin"]', 'candidate', 0, 0),
  ('NEIGHBOR', 'people_family', '["שכן", "שכנה"]', '["neighbor"]', 'candidate', 0, 0),
  ('GUEST', 'people_family', '["אורח", "אורחת"]', '["guest"]', 'candidate', 0, 0),
  ('TEACHER', 'people_family', '["מורה"]', '["teacher"]', 'candidate', 0, 0),
  ('STUDENT', 'people_family', '["תלמיד", "תלמידה", "סטודנט"]', '["student", "pupil"]', 'candidate', 0, 0),
  ('NAME', 'people_family', '["שם"]', '["name"]', 'candidate', 0, 0),
  ('THEY', 'people_family', '["הם", "הן"]', '["they"]', 'candidate', 0, 0),
  ('YOU_PLURAL', 'people_family', '["אתם", "אתן"]', '["you (plural)"]', 'candidate', 0, 0),
  ('MY', 'people_family', '["שלי"]', '["my", "mine"]', 'candidate', 0, 0),
  ('YOUR', 'people_family', '["שלך"]', '["your", "yours"]', 'candidate', 0, 0),
  ('GOOD_NIGHT', 'greetings', '["לילה טוב"]', '["good night"]', 'candidate', 0, 0),
  ('GOOD_AFTERNOON', 'greetings', '["צהריים טובים"]', '["good afternoon"]', 'candidate', 0, 0),
  ('HOW_ARE_YOU', 'greetings', '["מה שלומך", "מה נשמע"]', '["how are you"]', 'candidate', 0, 0),
  ('FINE_THANKS', 'greetings', '["בסדר תודה", "טוב תודה"]', '["fine thanks"]', 'candidate', 0, 0),
  ('NICE_TO_MEET', 'greetings', '["נעים מאוד", "נעים להכיר"]', '["nice to meet you"]', 'candidate', 0, 0),
  ('EXCUSE_ME', 'greetings', '["סליחה", "סלח לי"]', '["excuse me"]', 'candidate', 0, 0),
  ('YES', 'greetings', '["כן"]', '["yes"]', 'candidate', 0, 0),
  ('NO', 'greetings', '["לא"]', '["no"]', 'candidate', 0, 0),
  ('OK', 'greetings', '["בסדר", "אוקיי"]', '["okay"]', 'candidate', 0, 0),
  ('GOOD_LUCK', 'greetings', '["בהצלחה"]', '["good luck"]', 'candidate', 0, 0),
  ('SHABBAT_SHALOM', 'greetings', '["שבת שלום"]', '["Shabbat shalom"]', 'candidate', 0, 0),
  ('HAPPY_HOLIDAY', 'greetings', '["חג שמח"]', '["happy holiday"]', 'candidate', 0, 0),
  ('BLESSING', 'greetings', '["ברכה", "ברוך"]', '["blessing"]', 'candidate', 0, 0),
  ('WELCOME_BACK', 'greetings', '["ברוך שובך"]', '["welcome back"]', 'candidate', 0, 0),
  ('COME', 'actions', '["בא", "באה", "לבוא"]', '["come"]', 'candidate', 0, 0),
  ('SIT', 'actions', '["יושב", "לשבת"]', '["sit"]', 'candidate', 0, 0),
  ('STAND', 'actions', '["עומד", "לעמוד"]', '["stand"]', 'candidate', 0, 0),
  ('WALK', 'actions', '["הולך ברגל", "ללכת"]', '["walk"]', 'candidate', 0, 0),
  ('RUN', 'actions', '["רץ", "לרוץ"]', '["run"]', 'candidate', 0, 0),
  ('SLEEP', 'actions', '["ישן", "לישון"]', '["sleep"]', 'candidate', 0, 0),
  ('WAKE_UP', 'actions', '["מתעורר", "להתעורר", "קם"]', '["wake up"]', 'candidate', 0, 0),
  ('SEE', 'actions', '["רואה", "לראות"]', '["see"]', 'candidate', 0, 0),
  ('LOOK', 'actions', '["מסתכל", "להסתכל"]', '["look"]', 'candidate', 0, 0),
  ('HEAR', 'actions', '["שומע", "לשמוע"]', '["hear"]', 'candidate', 0, 0),
  ('SAY', 'actions', '["אומר", "להגיד", "לומר"]', '["say"]', 'candidate', 0, 0),
  ('TELL', 'actions', '["מספר", "לספר"]', '["tell"]', 'candidate', 0, 0),
  ('ASK', 'actions', '["שואל", "לשאול"]', '["ask"]', 'candidate', 0, 0),
  ('ANSWER', 'actions', '["עונה", "לענות", "תשובה"]', '["answer"]', 'candidate', 0, 0),
  ('EXPLAIN', 'actions', '["מסביר", "להסביר"]', '["explain"]', 'candidate', 0, 0),
  ('REPEAT', 'actions', '["חוזר", "לחזור על", "שוב"]', '["repeat"]', 'candidate', 0, 0),
  ('WRITE', 'actions', '["כותב", "לכתוב"]', '["write"]', 'candidate', 0, 0),
  ('READ', 'actions', '["קורא", "לקרוא"]', '["read"]', 'candidate', 0, 0),
  ('OPEN', 'actions', '["פותח", "לפתוח", "פתוח"]', '["open"]', 'candidate', 0, 0),
  ('CLOSE', 'actions', '["סוגר", "לסגור", "סגור"]', '["close"]', 'candidate', 0, 0),
  ('START', 'actions', '["מתחיל", "להתחיל"]', '["start"]', 'candidate', 0, 0),
  ('FINISH', 'actions', '["מסיים", "לסיים", "נגמר"]', '["finish"]', 'candidate', 0, 0),
  ('LOVE', 'actions', '["אוהב", "לאהוב"]', '["love", "like"]', 'candidate', 0, 0),
  ('LIKE', 'actions', '["מחבב", "אהבתי"]', '["like"]', 'candidate', 0, 0),
  ('THINK', 'actions', '["חושב", "לחשוב"]', '["think"]', 'candidate', 0, 0),
  ('REMEMBER', 'actions', '["זוכר", "לזכור"]', '["remember"]', 'candidate', 0, 0),
  ('FORGET', 'actions', '["שוכח", "לשכוח"]', '["forget"]', 'candidate', 0, 0),
  ('LIVE', 'actions', '["גר", "לגור", "חי"]', '["live"]', 'candidate', 0, 0),
  ('COOK', 'actions', '["מבשל", "לבשל"]', '["cook"]', 'candidate', 0, 0),
  ('CLEAN', 'actions', '["מנקה", "לנקות", "נקי"]', '["clean"]', 'candidate', 0, 0),
  ('WASH', 'actions', '["רוחץ", "לרחוץ", "שוטף"]', '["wash"]', 'candidate', 0, 0),
  ('PLAY', 'actions', '["משחק", "לשחק"]', '["play"]', 'candidate', 0, 0),
  ('MEET', 'actions', '["פוגש", "לפגוש"]', '["meet"]', 'candidate', 0, 0),
  ('CALL', 'actions', '["מתקשר", "להתקשר"]', '["call (phone)"]', 'candidate', 0, 0),
  ('SEND', 'actions', '["שולח", "לשלוח"]', '["send"]', 'candidate', 0, 0),
  ('RECEIVE', 'actions', '["מקבל", "לקבל"]', '["receive"]', 'candidate', 0, 0),
  ('BRING', 'actions', '["מביא", "להביא"]', '["bring"]', 'candidate', 0, 0),
  ('PUT', 'actions', '["שם", "לשים"]', '["put"]', 'candidate', 0, 0),
  ('FIND', 'actions', '["מוצא", "למצוא"]', '["find"]', 'candidate', 0, 0),
  ('LOSE', 'actions', '["מאבד", "לאבד"]', '["lose"]', 'candidate', 0, 0),
  ('SEARCH', 'actions', '["מחפש", "לחפש"]', '["search", "look for"]', 'candidate', 0, 0),
  ('CHANGE', 'actions', '["משנה", "לשנות", "להחליף"]', '["change"]', 'candidate', 0, 0),
  ('TRY', 'actions', '["מנסה", "לנסות"]', '["try"]', 'candidate', 0, 0),
  ('DRIVE', 'actions', '["נוהג", "לנהוג"]', '["drive"]', 'candidate', 0, 0),
  ('TRAVEL', 'actions', '["נוסע", "לנסוע"]', '["travel", "ride"]', 'candidate', 0, 0),
  ('RETURN', 'actions', '["חוזר", "לחזור"]', '["return"]', 'candidate', 0, 0),
  ('ENTER', 'actions', '["נכנס", "להיכנס"]', '["enter"]', 'candidate', 0, 0),
  ('EXIT', 'actions', '["יוצא", "לצאת"]', '["exit", "go out"]', 'candidate', 0, 0),
  ('SIGN_LANGUAGE_VERB', 'actions', '["מסמן", "לסמן"]', '["sign (use sign language)"]', 'candidate', 0, 0),
  ('TEACH', 'actions', '["מלמד", "ללמד"]', '["teach"]', 'candidate', 0, 0),
  ('PRAY', 'actions', '["מתפלל", "להתפלל"]', '["pray"]', 'candidate', 0, 0),
  ('REST', 'actions', '["נח", "לנוח"]', '["rest"]', 'candidate', 0, 0),
  ('CANCEL', 'actions', '["מבטל", "לבטל"]', '["cancel"]', 'candidate', 0, 0),
  ('AGREE', 'actions', '["מסכים", "להסכים"]', '["agree"]', 'candidate', 0, 0),
  ('ALLOW', 'actions', '["מותר", "להרשות"]', '["allow", "permitted"]', 'candidate', 0, 0),
  ('FORBID', 'actions', '["אסור"]', '["forbidden"]', 'candidate', 0, 0),
  ('HOW_MUCH_COST', 'questions', '["כמה עולה"]', '["how much does it cost"]', 'candidate', 0, 0),
  ('WHAT_TIME', 'questions', '["מה השעה"]', '["what time"]', 'candidate', 0, 0),
  ('WHERE_FROM', 'questions', '["מאיפה"]', '["where from"]', 'candidate', 0, 0),
  ('WHERE_TO', 'questions', '["לאן"]', '["where to"]', 'candidate', 0, 0),
  ('WHAT_NAME', 'questions', '["איך קוראים לך", "מה שמך"]', '["what is your name"]', 'candidate', 0, 0),
  ('WHY_NOT', 'questions', '["למה לא"]', '["why not"]', 'candidate', 0, 0),
  ('IS_IT_POSSIBLE', 'questions', '["אפשר"]', '["is it possible", "may I"]', 'candidate', 0, 0),
  ('BORED', 'feelings', '["משועמם", "משעמם"]', '["bored"]', 'candidate', 0, 0),
  ('SURPRISED', 'feelings', '["מופתע", "מופתעת"]', '["surprised"]', 'candidate', 0, 0),
  ('PROUD', 'feelings', '["גאה"]', '["proud"]', 'candidate', 0, 0),
  ('ASHAMED', 'feelings', '["מתבייש", "מתביישת"]', '["ashamed"]', 'candidate', 0, 0),
  ('CONFUSED', 'feelings', '["מבולבל", "מבולבלת"]', '["confused"]', 'candidate', 0, 0),
  ('LONELY', 'feelings', '["בודד", "בודדה"]', '["lonely"]', 'candidate', 0, 0),
  ('GRATEFUL', 'feelings', '["אסיר תודה", "מודה"]', '["grateful"]', 'candidate', 0, 0),
  ('SICK_FEELING', 'feelings', '["לא מרגיש טוב"]', '["not feeling well"]', 'candidate', 0, 0),
  ('HAPPY_FOR', 'feelings', '["שמח בשבילך"]', '["happy for you"]', 'candidate', 0, 0),
  ('FEAR', 'feelings', '["פחד"]', '["fear"]', 'candidate', 0, 0),
  ('HOPE', 'feelings', '["תקווה", "מקווה"]', '["hope"]', 'candidate', 0, 0),
  ('HOUSE_ROOM', 'home', '["חדר"]', '["room"]', 'candidate', 0, 0),
  ('KITCHEN', 'home', '["מטבח"]', '["kitchen"]', 'candidate', 0, 0),
  ('BATHROOM', 'home', '["שירותים", "אמבטיה"]', '["bathroom", "toilet"]', 'candidate', 0, 0),
  ('BED', 'home', '["מיטה"]', '["bed"]', 'candidate', 0, 0),
  ('TABLE', 'home', '["שולחן"]', '["table"]', 'candidate', 0, 0),
  ('CHAIR', 'home', '["כיסא"]', '["chair"]', 'candidate', 0, 0),
  ('DOOR', 'home', '["דלת"]', '["door"]', 'candidate', 0, 0),
  ('WINDOW', 'home', '["חלון"]', '["window"]', 'candidate', 0, 0),
  ('KEY', 'home', '["מפתח"]', '["key"]', 'candidate', 0, 0),
  ('LIGHT', 'home', '["אור", "מנורה"]', '["light", "lamp"]', 'candidate', 0, 0),
  ('WATER_TAP', 'home', '["ברז"]', '["tap"]', 'candidate', 0, 0),
  ('PHONE', 'home', '["טלפון", "פלאפון"]', '["phone"]', 'candidate', 0, 0),
  ('COMPUTER', 'home', '["מחשב"]', '["computer"]', 'candidate', 0, 0),
  ('TELEVISION', 'home', '["טלוויזיה"]', '["television"]', 'candidate', 0, 0),
  ('BOOK', 'home', '["ספר"]', '["book"]', 'candidate', 0, 0),
  ('BAG', 'home', '["תיק"]', '["bag"]', 'candidate', 0, 0),
  ('GLASSES', 'home', '["משקפיים"]', '["glasses"]', 'candidate', 0, 0),
  ('CLOCK', 'home', '["שעון"]', '["clock", "watch"]', 'candidate', 0, 0),
  ('MONEY_WALLET', 'home', '["ארנק"]', '["wallet"]', 'candidate', 0, 0),
  ('ELEVATOR', 'home', '["מעלית"]', '["elevator"]', 'candidate', 0, 0),
  ('STAIRS', 'home', '["מדרגות"]', '["stairs"]', 'candidate', 0, 0),
  ('FOOD', 'food_drink', '["אוכל"]', '["food"]', 'candidate', 0, 0),
  ('WATER', 'food_drink', '["מים"]', '["water"]', 'candidate', 0, 0),
  ('BREAD', 'food_drink', '["לחם"]', '["bread"]', 'candidate', 0, 0),
  ('MILK', 'food_drink', '["חלב"]', '["milk"]', 'candidate', 0, 0),
  ('COFFEE', 'food_drink', '["קפה"]', '["coffee"]', 'candidate', 0, 0),
  ('TEA', 'food_drink', '["תה"]', '["tea"]', 'candidate', 0, 0),
  ('JUICE', 'food_drink', '["מיץ"]', '["juice"]', 'candidate', 0, 0),
  ('MEAT', 'food_drink', '["בשר"]', '["meat"]', 'candidate', 0, 0),
  ('CHICKEN', 'food_drink', '["עוף"]', '["chicken"]', 'candidate', 0, 0),
  ('FISH', 'food_drink', '["דג"]', '["fish"]', 'candidate', 0, 0),
  ('EGG', 'food_drink', '["ביצה"]', '["egg"]', 'candidate', 0, 0),
  ('CHEESE', 'food_drink', '["גבינה"]', '["cheese"]', 'candidate', 0, 0),
  ('RICE', 'food_drink', '["אורז"]', '["rice"]', 'candidate', 0, 0),
  ('VEGETABLES', 'food_drink', '["ירקות", "ירק"]', '["vegetables"]', 'candidate', 0, 0),
  ('FRUIT', 'food_drink', '["פירות", "פרי"]', '["fruit"]', 'candidate', 0, 0),
  ('APPLE', 'food_drink', '["תפוח"]', '["apple"]', 'candidate', 0, 0),
  ('SALT', 'food_drink', '["מלח"]', '["salt"]', 'candidate', 0, 0),
  ('SUGAR', 'food_drink', '["סוכר"]', '["sugar"]', 'candidate', 0, 0),
  ('BREAKFAST', 'food_drink', '["ארוחת בוקר"]', '["breakfast"]', 'candidate', 0, 0),
  ('LUNCH', 'food_drink', '["ארוחת צהריים"]', '["lunch"]', 'candidate', 0, 0),
  ('DINNER', 'food_drink', '["ארוחת ערב"]', '["dinner"]', 'candidate', 0, 0),
  ('RESTAURANT', 'food_drink', '["מסעדה"]', '["restaurant"]', 'candidate', 0, 0),
  ('KOSHER', 'food_drink', '["כשר", "כשרות"]', '["kosher"]', 'candidate', 0, 0),
  ('TASTY', 'food_drink', '["טעים", "טעימה"]', '["tasty"]', 'candidate', 0, 0),
  ('CLOTHES', 'clothing', '["בגדים", "בגד"]', '["clothes"]', 'candidate', 0, 0),
  ('SHIRT', 'clothing', '["חולצה"]', '["shirt"]', 'candidate', 0, 0),
  ('PANTS', 'clothing', '["מכנסיים"]', '["trousers"]', 'candidate', 0, 0),
  ('SHOES', 'clothing', '["נעליים", "נעל"]', '["shoes"]', 'candidate', 0, 0),
  ('COAT', 'clothing', '["מעיל"]', '["coat"]', 'candidate', 0, 0),
  ('HAT', 'clothing', '["כובע"]', '["hat"]', 'candidate', 0, 0),
  ('KIPPAH', 'clothing', '["כיפה"]', '["kippah"]', 'candidate', 0, 0),
  ('BODY', 'health_help', '["גוף"]', '["body"]', 'candidate', 0, 0),
  ('HEAD', 'health_help', '["ראש"]', '["head"]', 'candidate', 0, 0),
  ('EYE', 'health_help', '["עין", "עיניים"]', '["eye"]', 'candidate', 0, 0),
  ('EAR', 'health_help', '["אוזן", "אוזניים"]', '["ear"]', 'candidate', 0, 0),
  ('MOUTH', 'health_help', '["פה"]', '["mouth"]', 'candidate', 0, 0),
  ('TOOTH', 'health_help', '["שן", "שיניים"]', '["tooth"]', 'candidate', 0, 0),
  ('HAND', 'health_help', '["יד", "ידיים"]', '["hand"]', 'candidate', 0, 0),
  ('LEG', 'health_help', '["רגל", "רגליים"]', '["leg"]', 'candidate', 0, 0),
  ('BACK', 'health_help', '["גב"]', '["back"]', 'candidate', 0, 0),
  ('STOMACH', 'health_help', '["בטן"]', '["stomach"]', 'candidate', 0, 0),
  ('HEART', 'health_help', '["לב"]', '["heart"]', 'candidate', 0, 0),
  ('HEADACHE', 'health_help', '["כאב ראש"]', '["headache"]', 'candidate', 0, 0),
  ('FEVER', 'health_help', '["חום"]', '["fever"]', 'candidate', 0, 0),
  ('COUGH', 'health_help', '["שיעול", "משתעל"]', '["cough"]', 'candidate', 0, 0),
  ('ALLERGY', 'health_help', '["אלרגיה"]', '["allergy"]', 'candidate', 0, 0),
  ('NURSE', 'health_help', '["אחות", "אח"]', '["nurse"]', 'candidate', 0, 0),
  ('CLINIC', 'health_help', '["מרפאה", "קופת חולים"]', '["clinic"]', 'candidate', 0, 0),
  ('PHARMACY', 'health_help', '["בית מרקחת"]', '["pharmacy"]', 'candidate', 0, 0),
  ('APPOINTMENT', 'health_help', '["תור"]', '["appointment"]', 'candidate', 0, 0),
  ('PRESCRIPTION', 'health_help', '["מרשם"]', '["prescription"]', 'candidate', 0, 0),
  ('TEST_MEDICAL', 'health_help', '["בדיקה"]', '["(medical) test"]', 'candidate', 0, 0),
  ('FIRE', 'health_help', '["שריפה", "אש"]', '["fire"]', 'candidate', 0, 0),
  ('ACCIDENT', 'health_help', '["תאונה"]', '["accident"]', 'candidate', 0, 0),
  ('DANGER', 'health_help', '["סכנה", "מסוכן"]', '["danger"]', 'candidate', 0, 0),
  ('CALL_HELP', 'health_help', '["הצילו"]', '["help! (call for help)"]', 'candidate', 0, 0),
  ('LOST', 'health_help', '["הלכתי לאיבוד", "אבוד"]', '["lost"]', 'candidate', 0, 0),
  ('SAFE', 'health_help', '["בטוח", "בטוחה"]', '["safe"]', 'candidate', 0, 0),
  ('DEAF', 'communication', '["חירש", "חירשת"]', '["deaf"]', 'candidate', 0, 0),
  ('HARD_OF_HEARING', 'communication', '["כבד שמיעה", "כבדת שמיעה"]', '["hard of hearing"]', 'candidate', 0, 0),
  ('HEARING', 'communication', '["שומע", "שומעת"]', '["hearing (person)"]', 'candidate', 0, 0),
  ('SIGN_LANGUAGE', 'communication', '["שפת סימנים"]', '["sign language"]', 'candidate', 0, 0),
  ('INTERPRETER', 'communication', '["מתורגמן", "מתורגמנית"]', '["interpreter"]', 'candidate', 0, 0),
  ('HEARING_AID', 'communication', '["מכשיר שמיעה"]', '["hearing aid"]', 'candidate', 0, 0),
  ('SUBTITLES', 'communication', '["כתוביות"]', '["subtitles", "captions"]', 'candidate', 0, 0),
  ('MESSAGE', 'communication', '["הודעה"]', '["message"]', 'candidate', 0, 0),
  ('VIDEO_CALL', 'communication', '["שיחת וידאו"]', '["video call"]', 'candidate', 0, 0),
  ('EMAIL', 'communication', '["אימייל", "דואר אלקטרוני"]', '["email"]', 'candidate', 0, 0),
  ('SLOWLY', 'communication', '["לאט"]', '["slowly"]', 'candidate', 0, 0),
  ('UNDERSTAND_NOT', 'communication', '["לא מבין", "לא הבנתי"]', '["don''t understand"]', 'candidate', 0, 0),
  ('WRITE_IT', 'communication', '["תכתוב לי", "בכתב"]', '["write it down"]', 'candidate', 0, 0),
  ('LANGUAGE', 'communication', '["שפה"]', '["language"]', 'candidate', 0, 0),
  ('HEBREW', 'communication', '["עברית"]', '["Hebrew"]', 'candidate', 0, 0),
  ('ARABIC', 'communication', '["ערבית"]', '["Arabic"]', 'candidate', 0, 0),
  ('ENGLISH', 'communication', '["אנגלית"]', '["English"]', 'candidate', 0, 0),
  ('WORD', 'communication', '["מילה"]', '["word"]', 'candidate', 0, 0),
  ('QUESTION', 'communication', '["שאלה"]', '["question"]', 'candidate', 0, 0),
  ('COUNTRY', 'places_transport', '["ארץ", "מדינה"]', '["country"]', 'candidate', 0, 0),
  ('ISRAEL', 'places_transport', '["ישראל"]', '["Israel"]', 'candidate', 0, 0),
  ('JERUSALEM', 'places_transport', '["ירושלים"]', '["Jerusalem"]', 'candidate', 0, 0),
  ('TEL_AVIV', 'places_transport', '["תל אביב"]', '["Tel Aviv"]', 'candidate', 0, 0),
  ('HAIFA', 'places_transport', '["חיפה"]', '["Haifa"]', 'candidate', 0, 0),
  ('SYNAGOGUE', 'places_transport', '["בית כנסת"]', '["synagogue"]', 'candidate', 0, 0),
  ('POST_OFFICE', 'places_transport', '["דואר"]', '["post office"]', 'candidate', 0, 0),
  ('SUPERMARKET', 'places_transport', '["סופר", "סופרמרקט"]', '["supermarket"]', 'candidate', 0, 0),
  ('MARKET', 'places_transport', '["שוק"]', '["market"]', 'candidate', 0, 0),
  ('PARK', 'places_transport', '["גן", "פארק"]', '["park"]', 'candidate', 0, 0),
  ('KINDERGARTEN', 'places_transport', '["גן ילדים"]', '["kindergarten"]', 'candidate', 0, 0),
  ('UNIVERSITY', 'places_transport', '["אוניברסיטה"]', '["university"]', 'candidate', 0, 0),
  ('OFFICE', 'places_transport', '["משרד"]', '["office"]', 'candidate', 0, 0),
  ('AIRPORT', 'places_transport', '["שדה תעופה"]', '["airport"]', 'candidate', 0, 0),
  ('PLANE', 'places_transport', '["מטוס"]', '["plane"]', 'candidate', 0, 0),
  ('BICYCLE', 'places_transport', '["אופניים"]', '["bicycle"]', 'candidate', 0, 0),
  ('PARKING', 'places_transport', '["חניה"]', '["parking"]', 'candidate', 0, 0),
  ('ROAD', 'places_transport', '["כביש"]', '["road"]', 'candidate', 0, 0),
  ('LEFT', 'places_transport', '["שמאל", "שמאלה"]', '["left"]', 'candidate', 0, 0),
  ('RIGHT', 'places_transport', '["ימין", "ימינה"]', '["right"]', 'candidate', 0, 0),
  ('STRAIGHT', 'places_transport', '["ישר"]', '["straight"]', 'candidate', 0, 0),
  ('NEAR', 'places_transport', '["קרוב", "קרובה"]', '["near"]', 'candidate', 0, 0),
  ('FAR', 'places_transport', '["רחוק", "רחוקה"]', '["far"]', 'candidate', 0, 0),
  ('HERE', 'places_transport', '["כאן", "פה"]', '["here"]', 'candidate', 0, 0),
  ('THERE', 'places_transport', '["שם"]', '["there"]', 'candidate', 0, 0),
  ('UP', 'places_transport', '["למעלה"]', '["up"]', 'candidate', 0, 0),
  ('DOWN', 'places_transport', '["למטה"]', '["down"]', 'candidate', 0, 0),
  ('INSIDE', 'places_transport', '["בפנים"]', '["inside"]', 'candidate', 0, 0),
  ('OUTSIDE', 'places_transport', '["בחוץ"]', '["outside"]', 'candidate', 0, 0),
  ('TICKET', 'places_transport', '["כרטיס"]', '["ticket"]', 'candidate', 0, 0),
  ('MUNICIPALITY', 'service_money', '["עירייה"]', '["municipality"]', 'candidate', 0, 0),
  ('NATIONAL_INSURANCE', 'service_money', '["ביטוח לאומי"]', '["National Insurance"]', 'candidate', 0, 0),
  ('FORM', 'service_money', '["טופס"]', '["form"]', 'candidate', 0, 0),
  ('ID_CARD', 'service_money', '["תעודת זהות"]', '["ID card"]', 'candidate', 0, 0),
  ('SIGNATURE', 'service_money', '["חתימה", "לחתום"]', '["signature"]', 'candidate', 0, 0),
  ('DOCUMENT', 'service_money', '["מסמך"]', '["document"]', 'candidate', 0, 0),
  ('ADDRESS', 'service_money', '["כתובת"]', '["address"]', 'candidate', 0, 0),
  ('PHONE_NUMBER', 'service_money', '["מספר טלפון"]', '["phone number"]', 'candidate', 0, 0),
  ('QUEUE_LINE', 'service_money', '["תור"]', '["queue", "line"]', 'candidate', 0, 0),
  ('CASH', 'service_money', '["מזומן"]', '["cash"]', 'candidate', 0, 0),
  ('CREDIT_CARD', 'service_money', '["כרטיס אשראי"]', '["credit card"]', 'candidate', 0, 0),
  ('CHEAP', 'service_money', '["זול", "זולה"]', '["cheap"]', 'candidate', 0, 0),
  ('EXPENSIVE', 'service_money', '["יקר", "יקרה"]', '["expensive"]', 'candidate', 0, 0),
  ('FREE_OF_CHARGE', 'service_money', '["חינם"]', '["free of charge"]', 'candidate', 0, 0),
  ('RECEIPT', 'service_money', '["קבלה"]', '["receipt"]', 'candidate', 0, 0),
  ('DISCOUNT', 'service_money', '["הנחה"]', '["discount"]', 'candidate', 0, 0),
  ('SALARY', 'service_money', '["משכורת"]', '["salary"]', 'candidate', 0, 0),
  ('SCHOOL_CLASS', 'education_work', '["כיתה"]', '["class (classroom)"]', 'candidate', 0, 0),
  ('LESSON', 'education_work', '["שיעור"]', '["lesson"]', 'candidate', 0, 0),
  ('HOMEWORK', 'education_work', '["שיעורי בית"]', '["homework"]', 'candidate', 0, 0),
  ('EXAM', 'education_work', '["מבחן"]', '["exam"]', 'candidate', 0, 0),
  ('MEETING', 'education_work', '["פגישה"]', '["meeting"]', 'candidate', 0, 0),
  ('MANAGER', 'education_work', '["מנהל", "מנהלת"]', '["manager"]', 'candidate', 0, 0),
  ('COLLEAGUE', 'education_work', '["עמית", "עמיתה"]', '["colleague"]', 'candidate', 0, 0),
  ('BREAK', 'education_work', '["הפסקה"]', '["break"]', 'candidate', 0, 0),
  ('VACATION', 'education_work', '["חופשה", "חופש"]', '["vacation"]', 'candidate', 0, 0),
  ('WEATHER', 'nature_weather', '["מזג אוויר"]', '["weather"]', 'candidate', 0, 0),
  ('SUN', 'nature_weather', '["שמש"]', '["sun"]', 'candidate', 0, 0),
  ('RAIN', 'nature_weather', '["גשם"]', '["rain"]', 'candidate', 0, 0),
  ('WIND', 'nature_weather', '["רוח"]', '["wind"]', 'candidate', 0, 0),
  ('COLD', 'nature_weather', '["קר", "קרה"]', '["cold"]', 'candidate', 0, 0),
  ('HOT', 'nature_weather', '["חם", "חמה"]', '["hot"]', 'candidate', 0, 0),
  ('SEA', 'nature_weather', '["ים"]', '["sea"]', 'candidate', 0, 0),
  ('TREE', 'nature_weather', '["עץ"]', '["tree"]', 'candidate', 0, 0),
  ('FLOWER', 'nature_weather', '["פרח"]', '["flower"]', 'candidate', 0, 0),
  ('DOG', 'nature_weather', '["כלב"]', '["dog"]', 'candidate', 0, 0),
  ('CAT', 'nature_weather', '["חתול"]', '["cat"]', 'candidate', 0, 0),
  ('BIRD', 'nature_weather', '["ציפור"]', '["bird"]', 'candidate', 0, 0),
  ('PRAYER', 'religion_holidays', '["תפילה"]', '["prayer"]', 'candidate', 0, 0),
  ('TORAH', 'religion_holidays', '["תורה"]', '["Torah"]', 'candidate', 0, 0),
  ('SHABBAT_CANDLES', 'religion_holidays', '["נרות שבת"]', '["Shabbat candles"]', 'candidate', 0, 0),
  ('KIDDUSH', 'religion_holidays', '["קידוש"]', '["kiddush"]', 'candidate', 0, 0),
  ('ROSH_HASHANA', 'religion_holidays', '["ראש השנה"]', '["Rosh Hashana"]', 'candidate', 0, 0),
  ('YOM_KIPPUR', 'religion_holidays', '["יום כיפור"]', '["Yom Kippur"]', 'candidate', 0, 0),
  ('SUKKOT', 'religion_holidays', '["סוכות"]', '["Sukkot"]', 'candidate', 0, 0),
  ('HANUKKAH', 'religion_holidays', '["חנוכה"]', '["Hanukkah"]', 'candidate', 0, 0),
  ('PURIM', 'religion_holidays', '["פורים"]', '["Purim"]', 'candidate', 0, 0),
  ('PESACH', 'religion_holidays', '["פסח"]', '["Passover"]', 'candidate', 0, 0),
  ('SHAVUOT', 'religion_holidays', '["שבועות"]', '["Shavuot"]', 'candidate', 0, 0),
  ('HOLIDAY', 'religion_holidays', '["חג"]', '["holiday"]', 'candidate', 0, 0),
  ('FAST_DAY', 'religion_holidays', '["צום"]', '["fast"]', 'candidate', 0, 0),
  ('BEAUTIFUL', 'descriptions_quantities', '["יפה"]', '["beautiful", "nice"]', 'candidate', 0, 0),
  ('EASY', 'descriptions_quantities', '["קל", "קלה"]', '["easy"]', 'candidate', 0, 0),
  ('HARD', 'descriptions_quantities', '["קשה"]', '["hard", "difficult"]', 'candidate', 0, 0),
  ('FAST', 'descriptions_quantities', '["מהר", "מהיר"]', '["fast"]', 'candidate', 0, 0),
  ('SLOW', 'descriptions_quantities', '["איטי", "איטית"]', '["slow"]', 'candidate', 0, 0),
  ('IMPORTANT', 'descriptions_quantities', '["חשוב", "חשובה"]', '["important"]', 'candidate', 0, 0),
  ('CORRECT', 'descriptions_quantities', '["נכון"]', '["correct", "true"]', 'candidate', 0, 0),
  ('WRONG', 'descriptions_quantities', '["לא נכון", "טעות"]', '["wrong", "mistake"]', 'candidate', 0, 0),
  ('SAME', 'descriptions_quantities', '["אותו דבר", "אותו"]', '["same"]', 'candidate', 0, 0),
  ('DIFFERENT', 'descriptions_quantities', '["שונה"]', '["different"]', 'candidate', 0, 0),
  ('ALL', 'descriptions_quantities', '["כל", "כולם"]', '["all"]', 'candidate', 0, 0),
  ('NOTHING', 'descriptions_quantities', '["כלום", "שום דבר"]', '["nothing"]', 'candidate', 0, 0),
  ('SOMETHING', 'descriptions_quantities', '["משהו"]', '["something"]', 'candidate', 0, 0),
  ('ENOUGH', 'descriptions_quantities', '["מספיק"]', '["enough"]', 'candidate', 0, 0),
  ('VERY', 'descriptions_quantities', '["מאוד"]', '["very"]', 'candidate', 0, 0),
  ('ONLY', 'descriptions_quantities', '["רק"]', '["only"]', 'candidate', 0, 0),
  ('ALSO', 'descriptions_quantities', '["גם"]', '["also"]', 'candidate', 0, 0),
  ('WITH', 'descriptions_quantities', '["עם"]', '["with"]', 'candidate', 0, 0),
  ('WITHOUT', 'descriptions_quantities', '["בלי"]', '["without"]', 'candidate', 0, 0),
  ('FULL', 'descriptions_quantities', '["מלא", "מלאה"]', '["full"]', 'candidate', 0, 0),
  ('EMPTY', 'descriptions_quantities', '["ריק", "ריקה"]', '["empty"]', 'candidate', 0, 0),
  ('READY', 'descriptions_quantities', '["מוכן", "מוכנה"]', '["ready"]', 'candidate', 0, 0),
  ('BUSY', 'descriptions_quantities', '["עסוק", "עסוקה"]', '["busy"]', 'candidate', 0, 0),
  ('FREE_AVAILABLE', 'descriptions_quantities', '["פנוי", "פנויה"]', '["available", "free"]', 'candidate', 0, 0);
